### ISSUE TITLE
Submodule missing premake5.lua script

### ISSUE THREAD

**Issue by lexzor** [programming-bros/Tag2D#2]
It seems the submodule glfw it's missing the premake5.lua script.

![image](https://github.com/user-attachments/assets/371bf5a8-aea8-4bb9-8788-0f846e2177b2)

Reproduce the error by deleting the repo from local then clone it again.

**Comment by lexzor** [comment]
Solved by adding the `premake5.lua` file from @CMDR-JohnAlex glfw repository under client/external/glfw after fetching the git module.

It seems the configuration has been broke by the commit 1c91ac12dde3081874789cb0b46d60e416d33e7f . 

An idea i think would be to have static files of premake5.lua for our external libraries and add the official repos as a submodule (both glad, glfw and future libraries).

**Comment by DaaaPaul** [comment]
Firstly im sorry thats my bad because I did that commit, I wasn't thinking clearly, I will learn from that.

But yes if Im understanding correctly I agree to have official repos as submodules, because currently it is glfw as submodule but not glad, and that is inconsistent.

**Comment by CMDR-JohnAlex** [comment]
glad has a repository, but it is only the generator and not the code we want. glad files are loaded with the OpenGL version you need with any extensions or options you choose from https://glad.dav1d.de/. Sadly means we can't use it as a submodule, but I plan to make any other third party tools like ImGUI to use submodules in future.

> An idea i think would be to have static files of premake5.lua for our external libraries and add the official repos as a submodule (both glad, glfw and future libraries).

True... that might be nicer actually. I've always just used my fork because then I can be sure my premake file is working every time I sync with the official glfw repository, and then I just need to clone or add my repo as a submodule and not have to worry about the premake files or if something will break.

**Comment by DaaaPaul** [comment]
It seems that now this issue is fixed? 

When I run `git submodule update --init --recursive --remote --force` it also clones the premake5.lua

**Comment by CMDR-JohnAlex** [comment]
Yup, fixed by e29f653566f8fab94e9011c9895035451755ca2e.
